# Generated by Django 4.2 on 2023-05-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
        ("carts", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartproducts",
            old_name="cart_id",
            new_name="cart",
        ),
        migrations.RenameField(
            model_name="cartproducts",
            old_name="product_id",
            new_name="product",
        ),
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="cart",
                through="carts.CartProducts",
                to="products.product",
            ),
        ),
    ]
