# Generated by Django 4.2 on 2023-05-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0003_rename_cart_id_cartproducts_cart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
