# Generated by Django 4.2 on 2023-05-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(related_name="order", to="products.product"),
        ),
    ]
