# Generated by Django 4.2 on 2023-05-08 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("id",)},
        ),
    ]
